### ISSUE TITLE
Berlin.freifunk.net and other berlin ssids seem to be missing

### ISSUE THREAD

**Issue by kertase** [WIStudent/FreifunkAutoConnectApp#14]
The berlin SSID is missing from the autoconnect list.

**Comment by WIStudent** [comment]
The ssids are managed in a separate repository [here](https://github.com/WIStudent/freifunk-ssids), but I can add the ssid for you. Are you sure that the ssid starts with an uppercase B? Most url like Freifunk ssids I have seen so far are using only lowercase letters. 

Concerning other ssids, I don't live in Berlin so I don't know what ssids are used there. If you know any other missing ssids, please submitt them. When I started this project there was no public list of all Freifunk ssids (at least I couldn't find one), all ssids were submitted by Freifunk users.

**Comment by kertase** [comment]
Sorry it is actually lower case, I‘ll submit missing ssids if I find any.

**Comment by WIStudent** [comment]
berlin.freifunk.net was added (https://github.com/WIStudent/freifunk-ssids/commit/72c230f875992e6bcda55dd4d2c5a4b91f22372e)
