### ISSUE TITLE
freiburg.freifunk.net is missing

### ISSUE THREAD

**Issue by ulfi** [WIStudent/FreifunkAutoConnectApp#17]
Hi,

it will be great, when the network ID can be at yorself edited.

So I miss my network ID:
freiburg.freifunk.net

Attention, at the offical page linked database is not updated since month ago.

The new page wich is referenced in the mailing list is
https://openfreiburg.de/freifunk/meshviewer/#!v:m

Regards
Ulf

**Comment by WIStudent** [comment]
Done. (SSIDs are managed in a separate repository, see commit https://github.com/WIStudent/freifunk-ssids/commit/ba8457e8e3810c086dd76ad560852c8dfdac43bb)
